'use client';

import { useEffect, useState } from 'react';
import { BookOpen, Plus } from 'lucide-react';

type Document = { id: string; title: string; category: string; version: string; referenceUrl: string; notes: string; updatedAt: string };
export default function SopRepository({ canManage }: { canManage: boolean }) {
  const [documents, setDocuments] = useState<Document[]>([]);
  const [form, setForm] = useState({ title: '', category: '', version: '', referenceUrl: '', notes: '' });
  const [message, setMessage] = useState('');
  const load = async () => { const response = await fetch('/api/sop', { cache: 'no-store' }); if (response.ok) setDocuments(await response.json() as Document[]); };
  useEffect(() => { void load(); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setMessage(''); const response = await fetch('/api/sop', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const result = await response.json() as { error?: string }; if (!response.ok) { setMessage(result.error || 'Dokumen belum tersimpan.'); return; } setForm({ title: '', category: '', version: '', referenceUrl: '', notes: '' }); setMessage('Dokumen tersimpan.'); await load(); };
  return <main className="main"><div className="content"><div className="head"><div><h1>Repositori SOP & Regulasi</h1><p>Dokumen acuan yang dapat dipilih saat menyusun respons.</p></div><a className="secondary" href="/">Kembali ke dashboard</a></div><section className="panel"><h2><BookOpen size={20} className="inline-icon" /> Dokumen aktif</h2>{documents.length ? <div className="list">{documents.map((document) => <div className="flow-item" key={document.id}><b>{document.title} · Versi {document.version}</b><small>{document.category}{document.notes ? ` · ${document.notes}` : ''}</small>{document.referenceUrl && <a href={document.referenceUrl} target="_blank" rel="noreferrer">Buka dokumen ↗</a>}</div>)}</div> : <p>Belum ada SOP atau regulasi aktif.</p>}</section>{canManage && <section className="panel"><h2><Plus size={20} className="inline-icon" /> Tambah dokumen</h2><form onSubmit={submit}><div className="grid-fields"><div className="field"><label>Judul *</label><input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></div><div className="field"><label>Kategori *</label><input required placeholder="SOP Operasional / Regulasi" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} /></div><div className="field"><label>Versi *</label><input required value={form.version} onChange={(e) => setForm({ ...form, version: e.target.value })} /></div><div className="field"><label>Tautan dokumen</label><input placeholder="https://..." value={form.referenceUrl} onChange={(e) => setForm({ ...form, referenceUrl: e.target.value })} /></div></div><div className="field"><label>Catatan</label><textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></div><div className="actions"><button className="primary">Simpan dokumen</button></div>{message && <p>{message}</p>}</form></section>}</div></main>;
}
