'use client';
import { useState, type ChangeEvent, type Dispatch, type SetStateAction } from 'react';
import { ArrowRight, Check, Clock3, FilePlus2, MapPin, Send, Ship, Users, X } from 'lucide-react';
import { googleMapsUrl, parseCoordinates } from './interactive-map';
import { readStakeholderRows } from './stakeholder-data';
import { AuditTrail, SopReferencePicker } from './workflow-panels';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';

export type ApprovalRecord = { approver_id: string; approver_name: string; requester_name: string; status: string; submitted_at: string; decided_at: string | null; decision_note: string | null };
export type ApprovalState = { record: ApprovalRecord | null; history: { action: string; note: string; createdAt: string; actorName: string }[] };
export type ApprovalDocument = { id: string; filename: string; sizeBytes: number };
type Props = { incident: { id: string; category: string; location: string; priority: string; created_at: string; data: Record<string, string | boolean> }; draft: Record<string, string | boolean>; setDraft: Dispatch<SetStateAction<Record<string, string | boolean>>>; approvers: { id: string; name: string; role: string }[]; approval: ApprovalState; documents: ApprovalDocument[]; currentUserId: string; isAdmin: boolean; canEdit: boolean; saving: boolean; uploading: boolean; onUpload: (event: ChangeEvent<HTMLInputElement>) => void; onDraft: () => void; onSubmit: () => void; onDecision: (decision: 'approved' | 'rejected', note: string) => void };
const formatDate = (s: string) => new Date(s).toLocaleString('id-ID', { dateStyle: 'medium', timeStyle: 'short' });

function ResponseDateTimePicker({ value, disabled, onChange }: { value: string; disabled: boolean; onChange: (value: string) => void }) {
  const selected = value ? new Date(`${value}:00`) : undefined;
  const time = value.includes('T') ? value.slice(11, 16) : '';
  const [hour = '00', minute = '00'] = time.split(':');
  const setDate = (next?: Date) => {
    if (!next) return;
    const date = `${next.getFullYear()}-${String(next.getMonth() + 1).padStart(2, '0')}-${String(next.getDate()).padStart(2, '0')}`;
    onChange(`${date}T${time || '00:00'}`);
  };
  const setTime = (nextHour: string, nextMinute: string) => {
    const date = value.split('T')[0];
    if (date) onChange(`${date}T${nextHour}:${nextMinute}`);
  };
  return <div className="date-time-picker"><Popover><PopoverTrigger asChild><button type="button" className="secondary date-time-trigger" disabled={disabled}><Clock3 size={16} />{selected ? selected.toLocaleDateString('id-ID', { day: '2-digit', month: 'long', year: 'numeric' }) : 'Pilih tanggal'}</button></PopoverTrigger><PopoverContent className="w-auto p-0" align="start"><Calendar mode="single" selected={selected} onSelect={setDate} initialFocus /></PopoverContent></Popover><select aria-label="Jam pelaksanaan format 24 jam" disabled={disabled} value={hour} onChange={(event) => setTime(event.target.value, minute)}>{Array.from({ length: 24 }, (_, index) => String(index).padStart(2, '0')).map((item) => <option key={item} value={item}>{item}</option>)}</select><select aria-label="Menit pelaksanaan" disabled={disabled} value={minute} onChange={(event) => setTime(hour, event.target.value)}>{Array.from({ length: 60 }, (_, index) => String(index).padStart(2, '0')).map((item) => <option key={item} value={item}>{item}</option>)}</select></div>;
}

export function ResponseApprovalForm({ incident, draft, setDraft, approvers, approval, documents, currentUserId, isAdmin, canEdit, saving, uploading, onUpload, onDraft, onSubmit, onDecision }: Props) {
  const [tab, setTab] = useState<'detail' | 'history'>('detail');
  const [decisionNote, setDecisionNote] = useState('');
  const record = approval.record;
  const pending = record?.status === 'pending';
  const editingDisabled = !!pending || !canEdit;
  const canDecide = pending && (isAdmin || record?.approver_id === currentUserId);
  const rows = readStakeholderRows(incident.data.stakeholderRoles);
  const coordinate = parseCoordinates(incident.data.coordinates);
  const update = (key: string, value: string | boolean) => setDraft((old) => ({ ...old, [key]: value }));
  return <div className="response-form">
    <div className="response-title"><span className="response-title-icon"><Ship size={24} /></span><div><h2>4. Tentukan Respons dan Persetujuan Pimpinan</h2><p>Susun tindak lanjut dan ajukan keputusan sebelum pelaksanaan.</p></div><span className={`response-status ${record?.status || ''}`}>{record?.status === 'pending' ? '◷ Menunggu persetujuan' : record?.status === 'rejected' ? '● Perlu revisi' : 'Rancangan respons'}</span></div>
    {!canEdit && !canDecide && <p className="response-hint">Tahap ini disusun oleh Penerima Informasi Internal. Anda dapat meninjau rencana, tetapi hanya Pelaksana Respons yang dapat mengisi tahap Pelaksanaan setelah rencana disetujui.</p>}
    <div className="response-columns"><div className="response-stack">
      <section className="response-section"><h3>A. Ringkasan informasi</h3><div className="response-summary"><span>ID Informasi</span><strong>{incident.id}</strong><span>Jenis kejadian</span><strong>{incident.category}</strong><span>Lokasi prioritas</span><strong>{incident.location} {coordinate && <a href={googleMapsUrl(coordinate)} target="_blank" rel="noopener noreferrer"><MapPin size={15} /> Lihat di peta</a>}</strong><span>Tingkat prioritas</span><strong>{incident.priority}</strong><span>Tanggal</span><strong>{formatDate(incident.created_at)}</strong></div></section>
      <section className="response-section"><h3>B. Tentukan jenis respons</h3><div className="response-pair"><fieldset disabled={editingDisabled}><legend>Jenis respons yang diperlukan *</legend>{['Patroli / Penindakan', 'Pengawasan / Monitoring', 'Koordinasi / Klarifikasi', 'Bantuan SAR', 'Lainnya'].map((item) => <label className="response-choice" key={item}><input type="radio" name="responseType" checked={draft.responseType === item} onChange={() => update('responseType', item)} />{item}</label>)}</fieldset><fieldset disabled={editingDisabled}><legend>Tingkat urgensi *</legend>{['Sangat Mendesak', 'Mendesak', 'Normal', 'Rutin'].map((item, index) => <label className="response-choice" key={item}><input type="radio" name="urgency" checked={draft.urgency === item} onChange={() => update('urgency', item)} />{item} <small>({['≤ 2 jam', '≤ 6 jam', '≤ 24 jam', '> 24 jam'][index]})</small></label>)}</fieldset></div></section>
      <section className="response-section"><h3>C. Rencana tindak lanjut</h3><div className="response-fields"><label>Tujuan respons *<textarea disabled={editingDisabled} maxLength={500} value={String(draft.responseGoal || '')} onChange={(e) => update('responseGoal', e.target.value)} placeholder="Hasil yang ingin dicapai" /></label><label>Uraian rencana tindakan *<textarea disabled={editingDisabled} maxLength={2000} value={String(draft.responsePlan || '')} onChange={(e) => update('responsePlan', e.target.value)} placeholder="Jelaskan tindakan, pemeriksaan, dan koordinasi" /></label><div className="response-field-grid"><label>Perkiraan waktu pelaksanaan *<ResponseDateTimePicker disabled={editingDisabled} value={String(draft.targetDate || '')} onChange={(value) => update('targetDate', value)} /></label><label>Estimasi durasi (jam) *<input disabled={editingDisabled} type="number" min="1" max="720" value={String(draft.durationHours || '')} onChange={(e) => update('durationHours', e.target.value)} /></label></div><label>Sumber daya / sarana *<input disabled={editingDisabled} maxLength={500} value={String(draft.resources || '')} onChange={(e) => update('resources', e.target.value)} placeholder="Kapal, personel, perlengkapan" /></label><div><strong><Users size={15} /> Stakeholder terlibat</strong><div className="response-chips">{rows.map((row) => <span key={`${row.kind}:${row.name}`}>{row.name}</span>)}{!rows.length && <small>Belum ada stakeholder yang ditetapkan.</small>}</div></div></div></section>
      <section className="response-section"><h3>D. Permintaan persetujuan pimpinan</h3><div className="response-fields"><label>Ditujukan kepada *<select disabled={editingDisabled} value={String(draft.approverId || '')} onChange={(e) => update('approverId', e.target.value)}><option value="">Pilih pimpinan terdaftar</option>{approvers.map((person) => <option key={person.id} value={person.id}>{person.name} {person.role === 'super_admin' ? '(Super Admin)' : '(Pimpinan)'}</option>)}</select></label>{!approvers.length && <small>Super Admin perlu mendaftarkan akun pimpinan pada Pengaturan Pengguna.</small>}<label>Catatan pengajuan<textarea disabled={editingDisabled} maxLength={500} value={String(draft.requestNote || '')} onChange={(e) => update('requestNote', e.target.value)} placeholder="Mohon arahan dan persetujuan untuk pelaksanaan respons" /></label></div></section>
    </div><div className="response-stack"><section className="response-section"><h3>E. Persetujuan pimpinan</h3><div className="response-tabs"><button type="button" className={tab === 'detail' ? 'selected' : ''} onClick={() => setTab('detail')}>Detail persetujuan</button><button type="button" className={tab === 'history' ? 'selected' : ''} onClick={() => setTab('history')}>Riwayat ({approval.history.length})</button></div>{tab === 'detail' ? <><div className="response-summary"><span>Nama pimpinan</span><strong>{record?.approver_name || 'Belum diajukan'}</strong><span>Tanggal pengajuan</span><strong>{record ? formatDate(record.submitted_at) : '—'}</strong><span>Status</span><strong>{record?.status === 'pending' ? 'Menunggu persetujuan' : record?.status === 'approved' ? 'Disetujui' : record?.status === 'rejected' ? 'Ditolak / revisi' : 'Belum diajukan'}</strong>{record?.decision_note && <><span>Catatan pimpinan</span><strong>{record.decision_note}</strong></>}</div>{canDecide && <div className="response-decision"><label>Catatan pimpinan<textarea maxLength={500} value={decisionNote} onChange={(e) => setDecisionNote(e.target.value)} placeholder="Isi arahan atau alasan penolakan" /></label><div className="response-pair"><button className="response-reject" disabled={saving} onClick={() => onDecision('rejected', decisionNote)}><X size={17} /> Tolak</button><button className="response-approve" disabled={saving} onClick={() => onDecision('approved', decisionNote)}><Check size={17} /> Setujui</button></div></div>}{pending && !canDecide && <p className="response-hint"><Clock3 size={16} /> Menunggu keputusan dari pimpinan yang dituju.</p>}</> : <div className="response-history">{approval.history.length ? approval.history.map((item, i) => <div key={i}><strong>{item.action} · {item.actorName}</strong><small>{formatDate(item.createdAt)}</small>{item.note && <p>{item.note}</p>}</div>) : <p>Belum ada riwayat pengajuan.</p>}</div>}</section>
    <section className="response-section"><h3>Lampiran pendukung (opsional)</h3><p className="response-hint">SOP, surat tugas, foto, atau dokumen pendukung. PDF, JPG, PNG; maksimal 10 MB, 5 berkas.</p><div className="response-files">{documents.map((file) => <a href={`/api/incidents/${encodeURIComponent(incident.id)}/approval-documents/${file.id}`} key={file.id} target="_blank" rel="noopener noreferrer"><FilePlus2 size={17} />{file.filename} <small>{Math.round(file.sizeBytes / 1024)} KB</small></a>)}<label className="response-upload"><FilePlus2 size={18} /> {uploading ? 'Mengunggah...' : 'Tambah lampiran'}<input type="file" accept=".pdf,.jpg,.jpeg,.png" multiple hidden disabled={editingDisabled || uploading || documents.length >= 5} onChange={onUpload} /></label></div></section>
    <section className="response-section"><h3>F. Notifikasi</h3><label className="response-choice"><input type="checkbox" disabled={editingDisabled} checked={draft.notifyStakeholders !== false} onChange={(e) => update('notifyStakeholders', e.target.checked)} />Tampilkan pembaruan kepada stakeholder terkait setelah disetujui</label><p className="response-hint">Notifikasi di dalam aplikasi. Pengiriman email dan WhatsApp memerlukan integrasi layanan tambahan.</p><div className="response-chips">{rows.filter((row) => row.kind === 'external').map((row) => <span key={row.name}>{row.name}</span>)}</div></section></div></div>
    <div className="response-actions">{canEdit && <><button className="secondary" disabled={saving || editingDisabled} onClick={onDraft}>Simpan draf</button><button className="primary" disabled={saving || editingDisabled || !approvers.length} onClick={onSubmit}><Send size={17} />{saving ? 'Menyimpan...' : record?.status === 'rejected' ? 'Ajukan ulang ke pimpinan' : 'Ajukan ke pimpinan'}<ArrowRight size={17} /></button></>}</div>
    <SopReferencePicker value={String(draft.sopReferenceId || '')} disabled={editingDisabled} onChange={(id, title) => setDraft((old) => ({ ...old, sopReferenceId: id, sopReferenceTitle: title }))} />
    <AuditTrail incidentId={incident.id} />
  </div>;
}
export function ApprovalSummary({ approval }: { approval: ApprovalState }) { if (!approval.record) return null; return <section className="panel"><h2>Persetujuan pimpinan</h2><p>{approval.record.approver_name} · {approval.record.status === 'approved' ? 'Disetujui' : approval.record.status}</p><p>Pengajuan: {formatDate(approval.record.submitted_at)}{approval.record.decided_at && ` · Keputusan: ${formatDate(approval.record.decided_at)}`}</p>{approval.record.decision_note && <p>Catatan: {approval.record.decision_note}</p>}</section>; }
