'use client';

import { useEffect, useState } from 'react';
import { AlertTriangle, ArrowRightLeft, ClipboardCheck, Clock3, Siren } from 'lucide-react';

type Row = { id: string; incidentId?: string; category: string; location: string; priority: string; reason?: string; note?: string; pic?: string; due?: string; progress?: string; assignedTo?: string; automatic?: number; createdAt?: string };
type Data = { overdue: Row[]; findings: Row[]; handoffs: Row[]; escalations: Row[]; generatedAt: string };
const Panel = ({ title, icon, rows, empty, render }: { title: string; icon: React.ReactNode; rows: Row[]; empty: string; render: (row: Row) => React.ReactNode }) => <section className="panel"><h2>{icon} {title} <span className="badge high">{rows.length}</span></h2>{rows.length ? <div className="list">{rows.map((row) => <div className="flow-item" key={row.id}><b>{row.incidentId || row.id} · {row.category}</b>{render(row)}</div>)}</div> : <p>{empty}</p>}</section>;
export default function LeadershipDashboard() {
  const [data, setData] = useState<Data | null>(null); const [error, setError] = useState('');
  useEffect(() => { void fetch('/api/leadership-dashboard', { cache: 'no-store' }).then(async (response) => { const result = await response.json() as Data & { error?: string }; if (!response.ok) throw new Error(result.error); setData(result); }).catch((reason) => setError(reason instanceof Error ? reason.message : 'Dashboard belum tersedia.')); }, []);
  if (error) return <main className="main"><div className="content"><p>{error}</p></div></main>;
  if (!data) return <main className="main"><div className="content"><p>Memuat dashboard pimpinan...</p></div></main>;
  return <main className="main"><div className="content"><div className="head"><div><h1>Dashboard Pimpinan</h1><p>Prioritas tindakan, pengawasan tenggat, temuan, pelimpahan, dan eskalasi.</p></div><a className="secondary" href="/">Kembali ke dashboard</a></div><div className="stats"><div className="stat"><Clock3 /><div><strong>{data.overdue.length}</strong><span>Tenggat terlewati</span></div></div><div className="stat"><ClipboardCheck /><div><strong>{data.findings.length}</strong><span>Temuan monitoring</span></div></div><div className="stat"><ArrowRightLeft /><div><strong>{data.handoffs.length}</strong><span>Pelimpahan aktif</span></div></div><div className="stat"><Siren /><div><strong>{data.escalations.length}</strong><span>Eskalasi aktif</span></div></div></div><div className="dashboard-grid"><Panel title="Kasus terlambat" icon={<Clock3 size={20} />} rows={data.overdue} empty="Tidak ada tindak lanjut yang melewati tenggat." render={(row) => <small>PIC: {row.pic} · Tenggat: {row.due} · Progres: {row.progress}</small>} /><Panel title="Temuan monitoring" icon={<ClipboardCheck size={20} />} rows={data.findings} empty="Belum ada temuan monitoring." render={(row) => <small>{row.note} · {row.progress}</small>} /><Panel title="Pelimpahan aktif" icon={<ArrowRightLeft size={20} />} rows={data.handoffs} empty="Tidak ada pelimpahan aktif." render={(row) => <small>Tujuan: {row.assignedTo} · {row.reason}</small>} /><Panel title="Eskalasi aktif" icon={<AlertTriangle size={20} />} rows={data.escalations} empty="Tidak ada eskalasi aktif." render={(row) => <small>{row.automatic ? 'Otomatis karena tenggat: ' : ''}{row.reason}</small>} /></div></div></main>;
}
